export const CART_ACTION_TYPES = {
  SET_IS_CART_OPEN: "SET_IS_CART_OPEN",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  FETCH_CART_ITEMS_START: "FETCH_CART_ITEMS_START",
  FETCH_CART_ITEMS_SUCCESS: "FETCH_CART_ITEMS_SUCCESS",
  FETCH_CART_ITEMS_FAILURE: "FETCH_CART_ITEMS_FAILURE",
};
